/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 abhishek2.glb 
*/

import React, { useEffect, useRef, useState} from 'react'
import { useGLTF, useAnimations,useFBX } from '@react-three/drei'
import { subscribe } from '../events'

export function Abhishek2Model({ shouldTalk,setAnimationDuration, ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/abhishek2.glb')
  const { actions } = useAnimations(animations, group);
  console.log("action -------useanimation ----value---",actions);


  // const {animations : idleAnimation} = useFBX("/models/idlebreath.fbx");
  // idleAnimation[0].name = "idlemen";
  // const {actions : idleaction } = useAnimations([idleAnimation[0]], group);
  // console.log("fbx file scene",idleaction);
  // console.log("action -----idle---",idleaction);

  useEffect(()=>{
    console.log("Subscribe it")
    subscribe("startAnimation",StartTalk)
      // window.addEventListener("startAnimation",(e)=>{ StartTalk(e);});
    },[]);

    
function StartTalk(data){
  console.log("REceived data ",data)
var talk=data.detail.talk;
//var talk=data.detail.talk;

    if (talk==true) {
      
      actions.talk.play();
    
      // idleaction.idlemen.stop()
      
      console.log("Enetered", "for Talk***********")
     
      
    } else {  
      console.log("Enetered", "DStop")

      
      actions.talk.stop();
     

      // group.current.position.set(-0.056, -0.034, 0.039);
    
      // idleaction.idlemen.reset().fadeIn(0.8).play();
      
    }
 

 
}

// position={[-0.056, -0.034, 0.039]} rotation={[-0.038, -0.038, -0.052]} scale={0.01}
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" position={[-0.056, -0.034, 0.039]} rotation={[-0.038, -0.038, -0.052]} scale={0.01}>
        <group name="rp_eric_rigged_001"  scale={0.01} >
          <primitive object={nodes.root} />
          <skinnedMesh name="rp_eric_rigged_001_geo" geometry={nodes.rp_eric_rigged_001_geo.geometry} material={materials['rp_eric_rigged_001_mat.001']} skeleton={nodes.rp_eric_rigged_001_geo.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/abhishek2.glb')
