/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/girllipsync.glb -o src/components/GirlAvatar.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function GirlAvatar(props) {
  const { nodes, materials } = useGLTF('/models/girllipsync.glb')
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <skinnedMesh geometry={nodes.Wolf3D_Hair.geometry}
       material={materials.Wolf3D_Hair}
        skeleton={nodes.Wolf3D_Hair.skeleton} />

      <skinnedMesh geometry={nodes.EyeLeft.geometry}
       material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton} />

      <skinnedMesh geometry={nodes.EyeRight.geometry} 
      material={materials.Wolf3D_Eye} 
      skeleton={nodes.EyeRight.skeleton} />

      <skinnedMesh geometry={nodes.Wolf3D_Head.geometry} 
      material={materials.Wolf3D_Skin} 
      skeleton={nodes.Wolf3D_Head.skeleton} />

      <skinnedMesh geometry={nodes.Wolf3D_Teeth.geometry}
       material={materials.Wolf3D_Teeth} 
       skeleton={nodes.Wolf3D_Teeth.skeleton} />

      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Top.geometry} 
      material={materials.Wolf3D_Outfit_Top}
       skeleton={nodes.Wolf3D_Outfit_Top.skeleton} />

      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
       material={materials.Wolf3D_Outfit_Bottom} 
       skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton} />

      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
       material={materials.Wolf3D_Outfit_Footwear} 
       skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton} />

      <skinnedMesh geometry={nodes.Wolf3D_Body.geometry}
       material={materials.Wolf3D_Body} 
       skeleton={nodes.Wolf3D_Body.skeleton} />
    </group>
  )
}

useGLTF.preload('/models/girllipsync.glb')
