/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/head.glb -o src/components/HeadAvatar.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function HeadAvatar(props) {
  const { nodes, materials } = useGLTF('/models/head.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Model.geometry} material={materials.Material} rotation={[0, -Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/models/head.glb')
