/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Male_jaddu.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Male_jaddu(props) {
  const { nodes, materials } = useGLTF('/models/Male_jaddu.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <primitive object={nodes.Root_M} />
        <skinnedMesh  geometry={nodes.pasted__polySurface16.geometry} material={materials['pasted__Material #29']} skeleton={nodes.pasted__polySurface16.skeleton} />
        <skinnedMesh  geometry={nodes.pasted__polySurface18.geometry} material={materials['pasted__Material #29']} skeleton={nodes.pasted__polySurface18.skeleton} />
        <skinnedMesh  geometry={nodes.pasted__polySurface19.geometry} material={materials['pasted__Material #29']} skeleton={nodes.pasted__polySurface19.skeleton} />
        <skinnedMesh geometry={nodes.pasted__polySurface68.geometry} material={materials.pasted__GumsMaterial2} skeleton={nodes.pasted__polySurface68.skeleton} />
        <skinnedMesh geometry={nodes.pasted__polySurface69.geometry} material={materials.pasted__GumsMaterial2} skeleton={nodes.pasted__polySurface69.skeleton} />
        <skinnedMesh geometry={nodes.pasted__polySurface70.geometry} material={materials.pasted__GumsMaterial2} skeleton={nodes.pasted__polySurface70.skeleton} />
        <skinnedMesh geometry={nodes.pasted__polySurface76.geometry} material={materials.pasted__GumsMaterial2} skeleton={nodes.pasted__polySurface76.skeleton} />
        <skinnedMesh geometry={nodes.Mesh005.geometry} material={materials['pasted__Material #30']} skeleton={nodes.Mesh005.skeleton} />
        <skinnedMesh geometry={nodes.Mesh005_1.geometry} material={materials['pasted__Material #29']} skeleton={nodes.Mesh005_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh007.geometry} material={materials.pasted__TeethMaterial2} skeleton={nodes.Mesh007.skeleton} />
        <skinnedMesh geometry={nodes.Mesh007_1.geometry} material={materials.pasted__GumsMaterial2} skeleton={nodes.Mesh007_1.skeleton} />
        <skinnedMesh geometry={nodes.Mesh009.geometry} material={materials.pasted__GumsMaterial2} skeleton={nodes.Mesh009.skeleton} />
        <skinnedMesh geometry={nodes.Mesh009_1.geometry} material={materials.pasted__TeethMaterial2} skeleton={nodes.Mesh009_1.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/Male_jaddu.glb')
