/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 walk.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function WalkModel(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/walk.glb')
  const { actions } = useAnimations(animations, group)
  console.log("actions",actions);
  useEffect(()=>{
    // actions.AnimationAction.play()
  },[])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="rp_nathan_animated_003_walking" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group name="rp_nathan_animated_003_walking_CTRL">
            <group name="Armature">
              <primitive object={nodes.rp_nathan_animated_003_walking_root} />
              <skinnedMesh name="rp_nathan_animated_003_walking_geo" geometry={nodes.rp_nathan_animated_003_walking_geo.geometry} material={materials.rp_nathan_animated_003_mat} skeleton={nodes.rp_nathan_animated_003_walking_geo.skeleton} />
            </group>
          </group>
          <group name="rp_nathan_animated_003_walking_geoGRP" />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/walk.glb')
